# -- name for this producer
name: kafka-producer
# -- the port to use
port: 3000
# -- pod count
replicaCount: 2

image: 
  # -- the image name to use
  name: osskit/dafka-producer
  # -- the image tag to use
  tag: '2.0'

# -- the path for healthchecks, used for liveness and readiness
healthcheckPath: /isAlive

resources:
  requests:
    # -- cpu requests
    cpu: '400m'
    # -- memory requests
    memory: '400Mi'
  limits:
    # -- cpu limits
    cpu: '800m'
    # -- memory limits
    memory: '800Mi'

metrics:
  # -- should prometheus scrape this server
  enabled: true
  # -- a path prometheus should scrape metrics from
  path: /metrics
  
auth:
  # -- sasl username
  saslUsername:
   # -- gcp secret resource for sasl password
  saslPasswordResource:
   # -- mount GCP secrets to Opaque secrets
  useOpaqueSecrets: true
  truststore:
     # -- gcp secret resource for truststore file
    truststoreResource:
     # -- gcp secret resource for truststore password
    truststorePasswordResource:
